use super::*;

/// 既定 `SevenKeys` プロパティのゲージ定義（後方互換）。
pub fn default_gauge_definitions() -> Vec<GaugeDefinition> {
    gauge_definitions_for(GaugeProperty::default())
}

/// 指定 `GaugeProperty` に対応するゲージ定義一式を返す。
/// beatoraja `GaugeProperty.java` の全ゲージ値をプロパティ別に引く。
pub fn gauge_definitions_for(property: GaugeProperty) -> Vec<GaugeDefinition> {
    gauge_definition_table(property).to_vec()
}

pub fn gauge_definitions_for_rule_mode(
    property: GaugeProperty,
    rule_mode: RuleMode,
) -> Vec<GaugeDefinition> {
    gauge_definitions_for_rule_mode_and_keymode(property, rule_mode, KeyMode::K7)
}

pub fn gauge_definitions_for_rule_mode_and_keymode(
    property: GaugeProperty,
    rule_mode: RuleMode,
    key_mode: KeyMode,
) -> Vec<GaugeDefinition> {
    match rule_mode {
        RuleMode::Beatoraja => gauge_definitions_for(property),
        RuleMode::Lr2Oraja => lr2oraja_gauge_definitions(),
        RuleMode::Dx => {
            if key_mode == KeyMode::K9 {
                dx_pop_gauge_definition_table().to_vec()
            } else {
                dx_gauge_definition_table().to_vec()
            }
        }
    }
}

pub(super) fn lr2oraja_gauge_definitions() -> Vec<GaugeDefinition> {
    let mut definitions = gauge_definition_table(GaugeProperty::Lr2).to_vec();
    for definition in &mut definitions {
        match definition.gauge_type {
            GaugeType::Hard => {
                definition.guts = LR2_HARD_GUTS;
                definition.death = 2.0;
            }
            GaugeType::ExHard | GaugeType::Hazard => {
                definition.death = 2.0;
            }
            GaugeType::Class | GaugeType::ExClass => {
                definition.guts = LR2_HARD_GUTS;
                definition.death = 2.0;
            }
            _ => {}
        }
    }
    definitions
}

/// beatoraja `GaugeProperty.java` の `GaugeElementProperty` 表。
pub(super) fn gauge_definition_table(property: GaugeProperty) -> [GaugeDefinition; 9] {
    match property {
        GaugeProperty::FiveKeys => [
            def(
                GaugeType::AssistEasy,
                Some(ClearType::AssistEasy),
                GaugeModifier::Total,
                2.0,
                100.0,
                20.0,
                50.0,
                [1.0, 1.0, 0.5, -1.5, -3.0, -0.5],
                &[],
            ),
            def(
                GaugeType::Easy,
                Some(ClearType::Easy),
                GaugeModifier::Total,
                2.0,
                100.0,
                20.0,
                75.0,
                [1.0, 1.0, 0.5, -1.5, -4.5, -1.0],
                &[],
            ),
            def(
                GaugeType::Normal,
                Some(ClearType::Normal),
                GaugeModifier::Total,
                2.0,
                100.0,
                20.0,
                75.0,
                [1.0, 1.0, 0.5, -3.0, -6.0, -2.0],
                &[],
            ),
            def(
                GaugeType::Hard,
                Some(ClearType::Hard),
                GaugeModifier::LimitIncrement,
                0.0,
                100.0,
                100.0,
                0.0,
                [0.0, 0.0, 0.0, -5.0, -10.0, -5.0],
                &[],
            ),
            def(
                GaugeType::ExHard,
                Some(ClearType::ExHard),
                GaugeModifier::ModifyDamage,
                0.0,
                100.0,
                100.0,
                0.0,
                [0.0, 0.0, 0.0, -10.0, -20.0, -10.0],
                &[],
            ),
            def(
                GaugeType::Hazard,
                None,
                GaugeModifier::None,
                0.0,
                100.0,
                100.0,
                0.0,
                [0.0, 0.0, 0.0, -100.0, -100.0, -100.0],
                &[],
            ),
            def(
                GaugeType::Class,
                Some(ClearType::Normal),
                GaugeModifier::None,
                0.0,
                100.0,
                100.0,
                0.0,
                [0.01, 0.01, 0.0, -0.5, -1.0, -0.5],
                &[],
            ),
            def(
                GaugeType::ExClass,
                Some(ClearType::Hard),
                GaugeModifier::None,
                0.0,
                100.0,
                100.0,
                0.0,
                [0.01, 0.01, 0.0, -1.0, -2.0, -1.0],
                &[],
            ),
            def(
                GaugeType::ExHardClass,
                Some(ClearType::ExHard),
                GaugeModifier::None,
                0.0,
                100.0,
                100.0,
                0.0,
                [0.01, 0.01, 0.0, -2.5, -5.0, -2.5],
                &[],
            ),
        ],
        GaugeProperty::SevenKeys => [
            def(
                GaugeType::AssistEasy,
                Some(ClearType::AssistEasy),
                GaugeModifier::Total,
                2.0,
                100.0,
                20.0,
                60.0,
                [1.0, 1.0, 0.5, -1.5, -3.0, -0.5],
                &[],
            ),
            def(
                GaugeType::Easy,
                Some(ClearType::Easy),
                GaugeModifier::Total,
                2.0,
                100.0,
                20.0,
                80.0,
                [1.0, 1.0, 0.5, -1.5, -4.5, -1.0],
                &[],
            ),
            def(
                GaugeType::Normal,
                Some(ClearType::Normal),
                GaugeModifier::Total,
                2.0,
                100.0,
                20.0,
                80.0,
                [1.0, 1.0, 0.5, -3.0, -6.0, -2.0],
                &[],
            ),
            def(
                GaugeType::Hard,
                Some(ClearType::Hard),
                GaugeModifier::LimitIncrement,
                0.0,
                100.0,
                100.0,
                0.0,
                [0.15, 0.12, 0.03, -5.0, -10.0, -5.0],
                HARD_GUTS,
            ),
            def(
                GaugeType::ExHard,
                Some(ClearType::ExHard),
                GaugeModifier::LimitIncrement,
                0.0,
                100.0,
                100.0,
                0.0,
                [0.15, 0.06, 0.0, -8.0, -16.0, -8.0],
                &[],
            ),
            def(
                GaugeType::Hazard,
                None,
                GaugeModifier::None,
                0.0,
                100.0,
                100.0,
                0.0,
                [0.15, 0.06, 0.0, -100.0, -100.0, -10.0],
                &[],
            ),
            def(
                GaugeType::Class,
                Some(ClearType::Normal),
                GaugeModifier::None,
                0.0,
                100.0,
                100.0,
                0.0,
                [0.15, 0.12, 0.06, -1.5, -3.0, -1.5],
                CLASS_GUTS,
            ),
            def(
                GaugeType::ExClass,
                Some(ClearType::Hard),
                GaugeModifier::None,
                0.0,
                100.0,
                100.0,
                0.0,
                [0.15, 0.12, 0.03, -3.0, -6.0, -3.0],
                &[],
            ),
            def(
                GaugeType::ExHardClass,
                Some(ClearType::ExHard),
                GaugeModifier::None,
                0.0,
                100.0,
                100.0,
                0.0,
                [0.15, 0.06, 0.0, -5.0, -10.0, -5.0],
                &[],
            ),
        ],
        GaugeProperty::Pms => [
            def(
                GaugeType::AssistEasy,
                Some(ClearType::AssistEasy),
                GaugeModifier::Total,
                2.0,
                120.0,
                30.0,
                65.0,
                [1.0, 1.0, 0.5, -1.0, -2.0, -2.0],
                &[],
            ),
            def(
                GaugeType::Easy,
                Some(ClearType::Easy),
                GaugeModifier::Total,
                2.0,
                120.0,
                30.0,
                85.0,
                [1.0, 1.0, 0.5, -1.0, -3.0, -3.0],
                &[],
            ),
            def(
                GaugeType::Normal,
                Some(ClearType::Normal),
                GaugeModifier::Total,
                2.0,
                120.0,
                30.0,
                85.0,
                [1.0, 1.0, 0.5, -2.0, -6.0, -6.0],
                &[],
            ),
            def(
                GaugeType::Hard,
                Some(ClearType::Hard),
                GaugeModifier::LimitIncrement,
                0.0,
                100.0,
                100.0,
                0.0,
                [0.15, 0.12, 0.03, -5.0, -10.0, -10.0],
                HARD_GUTS,
            ),
            def(
                GaugeType::ExHard,
                Some(ClearType::ExHard),
                GaugeModifier::LimitIncrement,
                0.0,
                100.0,
                100.0,
                0.0,
                [0.15, 0.06, 0.0, -10.0, -15.0, -15.0],
                &[],
            ),
            def(
                GaugeType::Hazard,
                None,
                GaugeModifier::None,
                0.0,
                100.0,
                100.0,
                0.0,
                [0.15, 0.06, 0.0, -100.0, -100.0, -100.0],
                &[],
            ),
            def(
                GaugeType::Class,
                Some(ClearType::Normal),
                GaugeModifier::None,
                0.0,
                100.0,
                100.0,
                0.0,
                [0.15, 0.12, 0.06, -1.5, -3.0, -3.0],
                CLASS_GUTS,
            ),
            def(
                GaugeType::ExClass,
                Some(ClearType::Hard),
                GaugeModifier::None,
                0.0,
                100.0,
                100.0,
                0.0,
                [0.15, 0.12, 0.03, -3.0, -6.0, -6.0],
                &[],
            ),
            def(
                GaugeType::ExHardClass,
                Some(ClearType::ExHard),
                GaugeModifier::None,
                0.0,
                100.0,
                100.0,
                0.0,
                [0.15, 0.06, 0.0, -5.0, -10.0, -10.0],
                &[],
            ),
        ],
        GaugeProperty::Keyboard => [
            def(
                GaugeType::AssistEasy,
                Some(ClearType::AssistEasy),
                GaugeModifier::Total,
                2.0,
                100.0,
                30.0,
                50.0,
                [1.0, 1.0, 0.5, -1.0, -2.0, -1.0],
                &[],
            ),
            def(
                GaugeType::Easy,
                Some(ClearType::Easy),
                GaugeModifier::Total,
                2.0,
                100.0,
                20.0,
                70.0,
                [1.0, 1.0, 0.5, -1.0, -3.0, -1.0],
                &[],
            ),
            def(
                GaugeType::Normal,
                Some(ClearType::Normal),
                GaugeModifier::Total,
                2.0,
                100.0,
                20.0,
                70.0,
                [1.0, 1.0, 0.5, -2.0, -4.0, -2.0],
                &[],
            ),
            def(
                GaugeType::Hard,
                Some(ClearType::Hard),
                GaugeModifier::LimitIncrement,
                0.0,
                100.0,
                100.0,
                0.0,
                [0.2, 0.2, 0.1, -4.0, -8.0, -4.0],
                HARD_GUTS,
            ),
            def(
                GaugeType::ExHard,
                Some(ClearType::ExHard),
                GaugeModifier::LimitIncrement,
                0.0,
                100.0,
                100.0,
                0.0,
                [0.2, 0.1, 0.0, -6.0, -12.0, -6.0],
                &[],
            ),
            def(
                GaugeType::Hazard,
                None,
                GaugeModifier::None,
                0.0,
                100.0,
                100.0,
                0.0,
                [0.2, 0.1, 0.0, -100.0, -100.0, -100.0],
                &[],
            ),
            def(
                GaugeType::Class,
                Some(ClearType::Normal),
                GaugeModifier::None,
                0.0,
                100.0,
                100.0,
                0.0,
                [0.2, 0.2, 0.1, -1.5, -3.0, -1.5],
                CLASS_GUTS,
            ),
            def(
                GaugeType::ExClass,
                Some(ClearType::Hard),
                GaugeModifier::None,
                0.0,
                100.0,
                100.0,
                0.0,
                [0.2, 0.2, 0.1, -3.0, -6.0, -3.0],
                &[],
            ),
            def(
                GaugeType::ExHardClass,
                Some(ClearType::ExHard),
                GaugeModifier::None,
                0.0,
                100.0,
                100.0,
                0.0,
                [0.2, 0.1, 0.0, -5.0, -10.0, -5.0],
                &[],
            ),
        ],
        GaugeProperty::Lr2 => [
            def(
                GaugeType::AssistEasy,
                Some(ClearType::AssistEasy),
                GaugeModifier::Total,
                2.0,
                100.0,
                20.0,
                60.0,
                [1.2, 1.2, 0.6, -3.2, -4.8, -1.6],
                &[],
            ),
            def(
                GaugeType::Easy,
                Some(ClearType::Easy),
                GaugeModifier::Total,
                2.0,
                100.0,
                20.0,
                80.0,
                [1.2, 1.2, 0.6, -3.2, -4.8, -1.6],
                &[],
            ),
            def(
                GaugeType::Normal,
                Some(ClearType::Normal),
                GaugeModifier::Total,
                2.0,
                100.0,
                20.0,
                80.0,
                [1.0, 1.0, 0.5, -4.0, -6.0, -2.0],
                &[],
            ),
            def(
                GaugeType::Hard,
                Some(ClearType::Hard),
                GaugeModifier::ModifyDamage,
                0.0,
                100.0,
                100.0,
                0.0,
                [0.1, 0.1, 0.05, -6.0, -10.0, -2.0],
                LR2_CLASS_GUTS,
            ),
            def(
                GaugeType::ExHard,
                Some(ClearType::ExHard),
                GaugeModifier::ModifyDamage,
                0.0,
                100.0,
                100.0,
                0.0,
                [0.1, 0.1, 0.05, -12.0, -20.0, -2.0],
                &[],
            ),
            def(
                GaugeType::Hazard,
                None,
                GaugeModifier::None,
                0.0,
                100.0,
                100.0,
                0.0,
                [0.15, 0.06, 0.0, -100.0, -100.0, -10.0],
                &[],
            ),
            def(
                GaugeType::Class,
                Some(ClearType::Normal),
                GaugeModifier::None,
                0.0,
                100.0,
                100.0,
                0.0,
                [0.1, 0.1, 0.05, -2.0, -3.0, -2.0],
                LR2_CLASS_GUTS,
            ),
            def(
                GaugeType::ExClass,
                Some(ClearType::Hard),
                GaugeModifier::None,
                0.0,
                100.0,
                100.0,
                0.0,
                [0.1, 0.1, 0.05, -6.0, -10.0, -2.0],
                LR2_CLASS_GUTS,
            ),
            def(
                GaugeType::ExHardClass,
                Some(ClearType::ExHard),
                GaugeModifier::None,
                0.0,
                100.0,
                100.0,
                0.0,
                [0.1, 0.1, 0.05, -12.0, -20.0, -2.0],
                &[],
            ),
        ],
    }
}

pub(super) fn dx_gauge_definition_table() -> [GaugeDefinition; 9] {
    [
        def(
            GaugeType::AssistEasy,
            Some(ClearType::AssistEasy),
            GaugeModifier::Iidx,
            2.0,
            100.0,
            22.0,
            60.0,
            [1.0, 1.0, 0.5, -1.6, -4.8, -1.6],
            &[],
        ),
        def(
            GaugeType::Easy,
            Some(ClearType::Easy),
            GaugeModifier::Iidx,
            2.0,
            100.0,
            22.0,
            80.0,
            [1.0, 1.0, 0.5, -1.6, -4.8, -1.6],
            &[],
        ),
        def(
            GaugeType::Normal,
            Some(ClearType::Normal),
            GaugeModifier::Iidx,
            2.0,
            100.0,
            22.0,
            80.0,
            [1.0, 1.0, 0.5, -2.0, -6.0, -2.0],
            &[],
        ),
        def(
            GaugeType::Hard,
            Some(ClearType::Hard),
            GaugeModifier::None,
            0.0,
            100.0,
            100.0,
            0.0,
            [0.16, 0.16, 0.0, -4.5, -9.0, -4.5],
            DX_HARD_GUTS,
        ),
        def(
            GaugeType::ExHard,
            Some(ClearType::ExHard),
            GaugeModifier::None,
            0.0,
            100.0,
            100.0,
            0.0,
            [0.16, 0.16, 0.0, -9.0, -18.0, -9.0],
            &[],
        ),
        def(
            GaugeType::Hazard,
            None,
            GaugeModifier::None,
            0.0,
            100.0,
            100.0,
            0.0,
            [0.16, 0.16, 0.0, -100.0, -100.0, -9.0],
            &[],
        ),
        def(
            GaugeType::Class,
            Some(ClearType::Normal),
            GaugeModifier::None,
            0.0,
            100.0,
            100.0,
            0.0,
            [0.16, 0.16, 0.04, -1.5, -2.5, -1.5],
            DX_HARD_GUTS,
        ),
        def(
            GaugeType::ExClass,
            Some(ClearType::Hard),
            GaugeModifier::None,
            0.0,
            100.0,
            100.0,
            0.0,
            [0.16, 0.16, 0.04, -3.0, -5.0, -3.0],
            &[],
        ),
        def(
            GaugeType::ExHardClass,
            Some(ClearType::ExHard),
            GaugeModifier::None,
            0.0,
            100.0,
            100.0,
            0.0,
            [0.16, 0.16, 0.04, -6.0, -10.0, -6.0],
            &[],
        ),
    ]
}

pub(super) fn dx_pop_gauge_definition_table() -> [GaugeDefinition; 9] {
    [
        def(
            GaugeType::AssistEasy,
            Some(ClearType::AssistEasy),
            GaugeModifier::Pop,
            2.0,
            120.0,
            30.0,
            65.0,
            [1.2, 1.2, 0.6, -1.02, -3.0, -3.0],
            &[],
        ),
        def(
            GaugeType::Easy,
            Some(ClearType::Easy),
            GaugeModifier::Pop,
            2.0,
            120.0,
            30.0,
            85.0,
            [1.2, 1.2, 0.6, -1.02, -3.0, -3.0],
            &[],
        ),
        def(
            GaugeType::Normal,
            Some(ClearType::Normal),
            GaugeModifier::Pop,
            2.0,
            120.0,
            30.0,
            85.0,
            [1.2, 1.2, 0.6, -2.04, -6.0, -6.0],
            &[],
        ),
        def(
            GaugeType::Hard,
            Some(ClearType::Hard),
            GaugeModifier::Pop,
            2.0,
            120.0,
            30.0,
            85.0,
            [1.2, 1.2, 0.6, -4.08, -12.0, -12.0],
            &[],
        ),
        def(
            GaugeType::ExHard,
            Some(ClearType::ExHard),
            GaugeModifier::Pop,
            2.0,
            120.0,
            30.0,
            85.0,
            [1.2, 1.2, 0.6, -8.16, -24.0, -24.0],
            &[],
        ),
        def(
            GaugeType::Hazard,
            None,
            GaugeModifier::None,
            0.0,
            100.0,
            100.0,
            0.0,
            [0.15, 0.06, 0.0, -100.0, -100.0, -100.0],
            &[],
        ),
        def(
            GaugeType::Class,
            Some(ClearType::Normal),
            GaugeModifier::None,
            0.0,
            100.0,
            100.0,
            0.0,
            [0.15, 0.15, 0.06, -1.5, -3.0, -3.0],
            DX_HARD_GUTS,
        ),
        def(
            GaugeType::ExClass,
            Some(ClearType::Hard),
            GaugeModifier::None,
            0.0,
            100.0,
            100.0,
            0.0,
            [0.15, 0.15, 0.03, -3.0, -6.0, -6.0],
            &[],
        ),
        def(
            GaugeType::ExHardClass,
            Some(ClearType::ExHard),
            GaugeModifier::None,
            0.0,
            100.0,
            100.0,
            0.0,
            [0.15, 0.15, 0.0, -5.0, -10.0, -10.0],
            &[],
        ),
    ]
}

pub(super) fn def(
    gauge_type: GaugeType,
    clear_type: Option<ClearType>,
    modifier: GaugeModifier,
    min: f32,
    max: f32,
    init: f32,
    border: f32,
    values: [f32; 6],
    guts: &'static [(f32, f32)],
) -> GaugeDefinition {
    GaugeDefinition {
        gauge_type,
        clear_type,
        modifier,
        min,
        max,
        init,
        border,
        death: 0.0,
        values,
        guts,
    }
}

// beatoraja HARD guts テーブル（7keys / PMS / KB 共通）。
pub(super) const HARD_GUTS: &[(f32, f32)] =
    &[(10.0, 0.4), (20.0, 0.5), (30.0, 0.6), (40.0, 0.7), (50.0, 0.8)];
// beatoraja CLASS guts テーブル（7keys / PMS / KB 共通）。
pub(super) const CLASS_GUTS: &[(f32, f32)] =
    &[(5.0, 0.4), (10.0, 0.5), (15.0, 0.6), (20.0, 0.7), (25.0, 0.8)];
// beatoraja LR2 CLASS / EXCLASS の guts。32% 未満で減衰量を 60% に弱める。
pub(super) const LR2_CLASS_GUTS: &[(f32, f32)] = &[(32.0, 0.6)];
// LR2oraja 0.8.3+ の LR2 HARD 系 guts。32% 未満で減衰量を 60% に弱める。
pub(super) const LR2_HARD_GUTS: &[(f32, f32)] = &[(32.0, 0.6)];
pub(super) const DX_HARD_GUTS: &[(f32, f32)] = &[(30.0, 0.5)];
